version: '3.8'

services:

  elasticsearch:
    container_name: my_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    container_name: my_kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://my_elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8005:8005"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    volumes:
      - .:/app
